<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Week 3 Notes/Exercises</title>
</head>

<body>
    <h1>WDD 330 Portfolio</h1>
    <h2>Week 5 Notes/Exercises</h2>
    <ul>
        <li><a href="team_activity/index.html">Team Activity</a></li>
        <li><a href="quiz_ninja_project/index.html">Quiz Ninja Project</a></li>
    </ul>
    <ul>
        <h3>Chapter 10: Testing and Debugging</h3>
        <li>Programmer errors are our responsibility because we are able to do something about them.</li>
        <li>An exception is an error that produces a return value that can then be used by the program to deal with the
            error.</li>
        <li>A warning can occur if there’s an error in the code that isn't enough to cause the program to crash. This
            means the program will continue to run after a warning</li>
        <li>Not all browsers will display a warning message.</li>
        <li>We need our program to fail loudly if it ever does during development.</li>
        <li>We should us the 'use strict': in our code so that there is an increased possibility of catching errors.
        </li>
        <li>Strict mode will use exceptions instead of warnings.</li>
        <li>You can even use strict mode on a per-function basis by adding the line inside a function. Strict mode will
            then only be applied to anything inside that function</li>
        <li>Passing a lint test is no guarantee that your code is correct, but it will mean it will be more consistent
            and less likely to have problems.</li>
        <li>There are seven more error objects used for specific errors:
            <pre>
            EvalError is not used in the current ECMAScript specification and only retained for backwards compatibility.
            
            RangeError is thrown when a number is outside an allowable range of values.
            
            ReferenceError is thrown when a reference is made to an item that doesn’t exist. For example, calling a function that hasn't been defined.
            
            SyntaxError is thrown when there’s an error in the code’s syntax.
            
            TypeError is thrown when there’s an error in the type of value used; for example, a string is used when a number is expected.
            
            URIError is thrown when there’s a problem encoding or decoding the URI.
            
            InternalError is a non-standard error that is thrown when an error occurs in the JavaScript engine. A common cause of this too much recursion.</pre>
        </li>
        <li>I feel like this is a really great example of how tyo use a throw in your code.
    <pre>
    function squareRoot(number) {
        'use strict';
        if (number < 0) {
            throw new RangeError('You can't find the square root of negative numbers')
        }
        return Math.sqrt(number);
    };
</pre>
        </li>
            <li>A simple test to check the validity of the function:  <pre>
    function itSquareRoots4() {
        return squareRoot(4) === 2;
    }
    </pre>
        </li>
        <li>Test-driven development(TDD) is the process of writing tests before any actual code.</li>
    </ul>

    <h2>Questions</h2>
    <ul>
        <li>Is Jest the most popular testing framework?</li>
        <li>Do all programmers write their own tests, or can that be done by someone else during the dev process?</li>
    </ul>
    <script src='js/main.js'></script>
</body>

</html>